//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjem
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonelKayıtTab
    {
        public int PersonelID { get; set; }
        public string PersonelAd { get; set; }
        public string PersonelSoyad { get; set; }
        public string Cinsiyet { get; set; }
        public string Sehir { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
    }
}
